<?php
/**
 * Author: metal
 * Email: metal
 */

namespace backend\modules\configuration\controllers;

use backend\modules\configuration\components\ConfigurationController;
use backend\modules\configuration\models\Configuration;
use backend\modules\configuration\models\ReleaseWidget;
use metalguardian\dateTimePicker\Widget;

/**
 * Class ReleaseController
 * @package backend\modules\configuration\controllers
 */
class ReleaseController extends ConfigurationController
{
    public function actionUpdate()
    {
        $temp = new Configuration();

        Widget::widget([
            'model' => $temp,
            'attribute' => '[release_start_date_time]value',
        ]);
        Widget::widget([
            'model' => $temp,
            'attribute' => '[release_finish_date_time]value',
        ]);

        foreach ($temp->getTranslationModels() as $language => $model) {
            Widget::widget([
                'model' => $model,
                'attribute' => '[' . $language . '][release_start_date_time]value',
            ]);
            Widget::widget([
                'model' => $model,
                'attribute' => '[' . $language . '][release_finish_date_time]value',
            ]);
        }

        return parent::actionUpdate(); // TODO: Change the autogenerated stub
    }


    /**
     * Have to return Model::className()
     *
     * @inheritdoc
     */
    public function getModelClass()
    {
        return ReleaseWidget::className();
    }
}
